name: observatory_api_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  markdown: ^0.7.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
