name: vm_service_lib
description: A library to access the VM Service API.
version: 3.21.0

author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/vm_service_drivers

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.0.2
  stream_transform: ^0.0.7

dev_dependencies:
  async: ^2.0.0
  markdown: ^2.0.0
  mockito: ^4.0.0
  path: ^1.0.0
  pedantic: ^1.7.0
  pub_semver: ^1.0.0
  test: ^1.0.0
