name: vm_service_lib
description: A library to access the VM Service API.
version: 0.3.3

author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/vm_service_drivers

environment:
  sdk: '>=1.13.0 <2.0.0'

dev_dependencies:
  markdown: ^0.11.0
  path: ^1.0.0
  pub_semver: ^1.0.0
